### PR TITLE
Add Drive Assist Features

### PR DESCRIPTION
**Pull request by ParkerMeyers**
Add Drive Assist Features:
     - Forward Snapping (If joysticks are within 15% of each other, they snap to each other for more accurate forwards)
     - SlewRateLimiter (Slows/smoothes changes between joystick movements, helps motor life)
Updated Shuffleboard to contain options for the new drive assist features
Rearranged shuffleboard format and added drive assist tab
Added drive curves back from arcade drive to tank drive

Curves may have to be tweaked because of the change to tank

### CODE REVIEW

**Comment by slyafwalrus** [comment]
We would have to see if 15% is too big of a difference. We should try this out on Wednesday.

**Comment by ParkerMeyers** [comment]
> We would have to see if 15% is too big of a difference. We should try this out on Wednesday.

From testing, I have found that around 18% is good, but yes, we will have to try this on Wednesday

**Comment by BrownGenius** [comment]
It is important to see how reproducible the behavior is between runs.  This
is especially important in autonomous mode.  You need to make sure you
account for as many possible factors that can affect the drivetrain.  E.g.
declining battery level, wheel/gear slippage, etc.

--- ɥsǝlıu

**Comment by ParkerMeyers** [comment]
We will have to test this tomorrow during the meeting, but keep in mind that most of the drive assist features, (EX: forward snapping and a lower slew rate limiter) will not be applied (or reduced) while the robot is in autonomous mode.

**Pull request closed without merging**
